/**
 * Life_OS v2 — Asset manifest reader.
 *
 * Reads /assets/manifest.json (generated by scripts/scan-assets.js)
 * to discover what audio files and GIFs are available.
 *
 * Run `node scripts/scan-assets.js` after adding/removing files.
 */

export interface AssetManifest {
  generatedAt: string;
  exercises: {
    gifs: AssetEntry[];
    thumbnails: AssetEntry[];
  };
  audio: {
    coaches: AssetEntry[];
    music: {
      exercise: AssetEntry[];
      meditation: AssetEntry[];
      focus: AssetEntry[];
    };
    sfx: AssetEntry[];
    counselor: AssetEntry[];
  };
  totals: { gifs: number; audio: number };
}

export interface AssetEntry {
  path: string;
  name: string;
  size: number;
}

let _cache: AssetManifest | null = null;

export async function getAssetManifest(): Promise<AssetManifest> {
  if (_cache) return _cache;
  try {
    const res = await fetch("/assets/manifest.json");
    if (!res.ok) throw new Error("Manifest not found");
    _cache = await res.json();
    return _cache;
  } catch {
    return {
      generatedAt: "",
      exercises: { gifs: [], thumbnails: [] },
      audio: {
        coaches: [],
        music: { exercise: [], meditation: [], focus: [] },
        sfx: [],
        counselor: [],
      },
      totals: { gifs: 0, audio: 0 },
    };
  }
}

export function getGifPath(exerciseId: string, manifest?: AssetManifest): string | null {
  if (!manifest) return null;
  const gif = manifest.exercises.gifs.find(
    (g) => g.name.replace(/\.(gif|webp|png)$/i, "") === exerciseId
  );
  return gif?.path ?? null;
}

export function formatFileSize(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(0)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}
